/* TREINAMENTO 19 AUTORELACIONAMENTO PRÉ-REQUISITO DE CURSO*/

-- NESSE EXEMPLO PODE USAR UMA TABELA PARA SE RELACIONAR COM ELA MESMA

CREATE DATABASE AUTORELACIONAMENTO;
USE AUTORELACIONAMENTO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT

);

-- COLOCANDO CHAVE ESTRANGEIRA
ALTER TABLE CURSOS
ADD CONSTRAINT FK_PREREQ_PK_CURSOS
FOREIGN KEY (ID_PREREQ)
REFERENCES CURSOS (IDCURSO);

-- USAMOS UM DADO PARA SE RELACIONAR COM OUTRO DADO COMO REQUISITOS DO CURSO

INSERT INTO CURSOS VALUES (NULL,'BD RELACIONAL',20,400,NULL);
INSERT INTO CURSOS VALUES (NULL,'BUSINESS INTELLIGENCE',40,800,1);
INSERT INTO CURSOS VALUES (NULL,'RELATORIOS AVANCADOS',206,400,2);
INSERT INTO CURSOS VALUES (NULL,'LÓGICA DE PROGRAMAÇÃO',25,300,NULL);
INSERT INTO CURSOS VALUES (NULL,'RUBY',80,150,4);

SELECT * FROM CURSOS;

SELECT NOME,VALOR, HORAS, IFNULL(ID_PREREQ, "SEM REQ") REQUISITOS
FROM CURSOS;

/*TRAZ OS RESULTADOS DE NOME,VALOR,HORAS E O NOME DO PRE REQUISITO DO CURSO USANDO LEFT JOIN
PARA TRAZER TODOS OS CURSOS ATÉ OS QUE NÃO TEM PRE REQUISITOS*/

SELECT C.NOME AS "CURSOS",C.VALOR AS "CARGA",C.HORAS,IFNULL(P.NOME,'******') AS "PRÉ-REQUISITO"
FROM CURSOS C
LEFT JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;