/* TREINAMENTO 19 AUTORELACIONAMENTO PRÉ-REQUISITO DE CURSO*/

-- NESSE EXEMPLO PODE USAR UMA TABELA PARA SE RELACIONAR COM ELA MESMA



-- COLOCANDO CHAVE ESTRANGEIRA


-- USAMOS UM DADO PARA SE RELACIONAR COM OUTRO DADO COMO REQUISITOS DO CURSO



/*TRAZ OS RESULTADOS DE NOME,VALOR,HORAS E O NOME DO PRE REQUISITO DO CURSO USANDO LEFT JOIN
PARA TRAZER TODOS OS CURSOS ATÉ OS QUE NÃO TEM PRE REQUISITOS*/

