/* EXERCÍCIOS COMPLETOS DA AULA 1 ATÉ 5 DE TREINAMENTO*/

/* 01   CRIANDO O BANCO DE DADOS*/

CREATE DATABASE DADOS;

/*VERIFICANDO SE O BANCO FOI CRIADO*/
SHOW DATABASES; 

/*USANDO O BANCO DE DADOS CRIADO*/
USE DADOS;

/* 02   CRIANDO A TABELA */

CREATE TABLE REGISTROS(

NOME VARCHAR(50),
TELEFONE VARCHAR(20),
IDADE INT(10),
CIDADE VARCHAR(20)


);

/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/
DESC REGISTROS;
SHOW TABLES;

/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/

INSERT INTO REGISTROS(NOME,TELEFONE,IDADE,CIDADE) VALUES('Maxswell','117458852',30,'São Paulo');
INSERT INTO REGISTROS(NOME,TELEFONE,IDADE,CIDADE) VALUES('Lucas Lima','214581252',30,'Rio de Janeiro');
INSERT INTO REGISTROS(NOME,TELEFONE,IDADE,CIDADE) VALUES('Fernanda','2112587252',18,'Rio de Janeiro');
INSERT INTO REGISTROS(NOME,TELEFONE,IDADE,CIDADE) VALUES('Bianca','1165156545',19,'São Paulo');


INSERT INTO REGISTROS(NOME,TELEFONE,IDADE,CIDADE) VALUES
('Paula','214512568',25,'Rio de Janeiro'),
('Matheus','11458552',27,'São Paulo'),
('Sandro','112464252',34,'São Paulo'),
('Daniela','6165156545',29,'Goiás');

/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/

SELECT NOME,IDADE FROM REGISTROS WHERE CIDADE ='Rio de janeiro';

/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/

SELECT NOME,IDADE,CIDADE FROM REGISTROS WHERE CIDADE LIKE '%Paulo';
SELECT NOME,IDADE,CIDADE FROM REGISTROS WHERE CIDADE LIKE 'Rio%';

/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/
SELECT NOME,CIDADE,IDADE FROM REGISTROS WHERE CIDADE ='Rio de janeiro' or IDADE='15';   

/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/

SELECT NOME,CIDADE, IDADE FROM REGISTROS WHERE IDADE='30' AND CIDADE='São Paulo';

/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/

SELECT CIDADE, COUNT(*) AS 'CONTAGEM TOTAL' FROM REGISTROS GROUP BY CIDADE;


/* EXERCÍCIOS FINALIZADO E CORRETO, COM BANCO CRIADO, TABELAS,INSERT,SELECT, FILTROS DE DESEMPENHO DE BUSCAS*/




/* EXERCPICIOS SEMANAL DIA 16/01/2023 USE A MESMA BASE DE PERGUNTAS E MONTE O BANCO*/


/* 01   CRIANDO O BANCO DE DADOS*/

CREATE DATABASE EXERCICIO;



/*VERIFICANDO SE O BANCO FOI CRIADO*/
SHOW DATABASES;



/*USANDO O BANCO DE DADOS CRIADO*/
USE EXERCICIO;

/* 02   CRIANDO A TABELA */

CREATE TABLE REGISTROS(

NOME VARCHAR(100),
IDADE CHAR(2),
TELEFONE VARCHAR(20),
ENDERECO VARCHAR(100)


);




/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/

DESCRIBE REGISTROS;

/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/

INSERT INTO REGISTROS(NOME,IDADE,TELEFONE,ENDERECO) VALUES ('Maxswell Diniz',30,'11946742182','São Paulo'),('Matheus Rodriguez',25,'2169855534','Rio de Janeiro'),
('Camila Muniz',18,'1156589845','São Paulo'),('Bruna Martinz',35,'216987787845','Rio de Janeiro'),('Sandra Brito',32,'1146478787','São Paulo'),('Breno Junior',26,'1655487788','Minas Gerais');



/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/

SELECT * FROM REGISTROS;

SELECT NOME,ENDERECO FROM REGISTROS WHERE IDADE;

SELECT NOME,IDADE FROM REGISTROS WHERE ENDERECO='São Paulo';


/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/

SELECT NOME,ENDERECO,IDADE FROM REGISTROS WHERE ENDERECO LIKE '%Janeiro';

SELECT NOME,ENDERECO,IDADE FROM REGISTROS WHERE ENDERECO LIKE 'Rio%';



/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/

SELECT NOME,ENDERECO,IDADE FROM REGISTROS WHERE ENDERECO='Rio de Janeiro' OR IDADE='15';


/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/

SELECT NOME,ENDERECO,IDADE FROM REGISTROS WHERE IDADE='30' AND ENDERECO='São Paulo';


/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E GRUPOS DE REGISTROS SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/

SELECT ENDERECO, COUNT(*) AS 'CONTAGEM' FROM REGISTROS WHERE ENDERECO ='São Paulo';


/* REALIZANDO A CONTAGEM COM SEPARAÇÃO DE GRUPOS COMPUTADOS*/
SELECT ENDERECO, COUNT(*) AS 'CONTAGEM' FROM REGISTROS  GROUP BY ENDERECO;



/* TREINAMENTO DA SEMANA DIA 17-01-2023 */

/* 01   CRIANDO O BANCO DE DADOS*/

CREATE DATABASE DADOS;





/*VERIFICANDO SE O BANCO FOI CRIADO*/
SHOW DATABASES;




/*USANDO O BANCO DE DADOS CRIADO*/

USE DADOS;


/* 02   CRIANDO A TABELA */

CREATE TABLE REGISTROS(

NOME VARCHAR(100),
IDADE CHAR(2),
TELEFONE VARCHAR(20),
ENDERECO VARCHAR(100)


);






/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/

DESCRIBE REGISTROS;



/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/

INSERT INTO REGISTROS(NOME,IDADE,TELEFONE,ENDERECO) VALUES ('Maxswell Diniz',30,'115644523','São Paulo'),('Camila',25,'116985858','São Paulo'),('Fernanda Rodrigues',30,'214545454','Rio de Janeiro'),
('Sandra Madalena',30,'218546898787','Rio de Janeiro'),('Paulo Ricardo',26,'6148787878','Minas Gerais');




/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/

SELECT * FROM REGISTROS;



/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%Paulo';
SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE 'Rio%';
SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%Gerais';




/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO='Rio de Janeiro' OR IDADE='15' or NOME='Maxswell Diniz';





/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE IDADE='25' AND ENDERECO='São Paulo';



/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E GRUPOS DE REGISTROS SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/

SELECT ENDERECO, COUNT(*) AS 'CONTADOR' FROM REGISTROS GROUP BY ENDERECO;






/*#################################################################################################################################*/

/* 01   CRIANDO O BANCO DE DADOS*/

CREATE DATABASE DADOS;




/*VERIFICANDO SE O BANCO FOI CRIADO*/
SHOW DATABASES;




/*USANDO O BANCO DE DADOS CRIADO*/
USE DADOS;


/* 02   CRIANDO A TABELA */

CREATE TABLE REGISTROS(

NOME VARCHAR(100),
IDADE CHAR(2),
TELEFONE VARCHAR(100),
ENDERECO VARCHAR(100)




);






/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/

DESCRIBE REGISTROS;


/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/

INSERT INTO REGISTROS(NOME,IDADE,TELEFONE,ENDERECO) VALUES ('Maxswell Diniz',30,'1146445454','São Paulo'),('Fernanda',26,'214545545','Rio de Janeiro'),
('Bruno',31,'1145454544','São Paulo'),('Camila',30,'2145454545','Rio de Janeiro'),('Sandro',18,'11445454545','São Paulo'),('Patrique',32,'61','Minas Gerais');




/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/

SELECT * FROM REGISTROS;



/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%Janeiro';
SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE 'São%';




/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/

SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%janeiro' OR IDADE='15';
SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE ENDERECO='São Paulo' OR IDADE='30';




/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/

SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE IDADE='30' AND ENDERECO like '%Paulo';




/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E GRUPOS DE REGISTROS SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/

SELECT NOME,IDADE,ENDERECO, COUNT(*) AS 'CONTAGEM DE REGISTROS' FROM REGISTROS GROUP BY IDADE;
SELECT NOME,IDADE,ENDERECO, COUNT(*) AS 'CONTAGEM DE REGISTROS' FROM REGISTROS GROUP BY ENDERECO;








/*#################################################################################################################################*/


/* 01   CRIANDO O BANCO DE DADOS*/

CREATE DATABASE DADOS;





/*VERIFICANDO SE O BANCO FOI CRIADO*/
SHOW DATABASES;



/*USANDO O BANCO DE DADOS CRIADO*/
USE DADOS;


/* 02   CRIANDO A TABELA */

CREATE TABLE REGISTROS(

NOME VARCHAR(100),
IDADE CHAR(2),
TELEFONE VARCHAR(20),
ENDERECO VARCHAR(100)


);






/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/
DESC REGISTROS;


/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/

INSERT INTO REGISTROS(NOME,IDADE,TELEFONE,ENDERECO) VALUES ('Maxswell',30,'114545454','São Paulo'),('Bruna',25,'21487878','Rio de janeiro'),
('Talita',18,'11787878','São Paulo'),('Ricardo',30,'21454545','Rio de Janeiro'),('Maria',45,'614545454','Minas Gerais');



('',,'',''),

/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/

SELECT NOME AS 'CLIENTES', IDADE,TELEFONE,ENDERECO FROM REGISTROS;
SELECT * FROM REGISTROS;



/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%Paulo';
SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE 'Rio%';




/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO='Rio de Janeiro' or IDADE='15';




/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE IDADE='30' AND ENDERECO='São Paulo';
SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE IDADE='30' AND ENDERECO LIKE '%Paulo';



/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E GRUPOS DE REGISTROS SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/

SELECT NOME,ENDERECO, COUNT(*) AS 'TOTAL' FROM REGISTROS GROUP BY ENDERECO;


/* REALIZANDO A CONTAGEM COM SEPARAÇÃO DE GRUPOS COMPUTADOS*/

/* 01   CRIANDO O BANCO DE DADOS*/
CREATE DATABASE DADOS;




/*VERIFICANDO SE O BANCO FOI CRIADO*/

SHOW DATABASES;


/*USANDO O BANCO DE DADOS CRIADO*/
USE DADOS;


/* 02   CRIANDO A TABELA */

CREATE TABLE REGISTROS(

NOME VARCHAR(100),
IDADE CHAR(2),
TELEFONE varchar(20),
ENDERECO VARCHAR(100)




);






/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/
DESCRIBE REGISTROS;

/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/

INSERT INTO REGISTROS(NOME,IDADE,TELEFONE,ENDERECO) VALUES ('Maxswell DIniz',30,'116487545','São Paulo'),('Carla Oliveira',39,'2196454545','Rio de Janeiro'),
('Bruna',25,'116466455','São Paulo'),('Camila',30,'6145458454','Minas Gerais'),

INSERT INTO REGISTROS(NOME,IDADE,TELEFONE,ENDERECO) VALUES 
('Matheus',31,'61454887','Minas Gerais');




/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/

SELECT * FROM REGISTROS;



/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/

SELECT NOME AS 'Usuário',IDADE,ENDERECO AS 'CIDADE' FROM REGISTROS WHERE ENDERECO  ='São Paulo';
SELECT NOME AS 'Usuário',IDADE,ENDERECO AS 'CIDADE' FROM REGISTROS WHERE ENDERECO  ='Rio de Janeiro';
SELECT NOME AS 'Usuário',IDADE,ENDERECO AS 'CIDADE' FROM REGISTROS WHERE ENDERECO  ='Minas Gerais';


SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%Paulo';
SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE 'Rio%';
SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%de%';




/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/

SELECT ENDERECO, COUNT(*) FROM REGISTROS GROUP BY ENDERECO;

SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE ENDERECO ='Rio de Janeiro' OR idade='15';

SELECT NOME,IDADE,ENDERECO FROM REGISTROS WHERE (ENDERECO ='Rio de Janeiro' OR idade='15' and ENDERECO='São Paulo' or endereco='Minas Gerais');




/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/

SELECT NOME,IDADE,ENDERECO, COUNT(*) FROM REGISTROS GROUP BY IDADE;

SELECT NOME,IDADE,ENDERECO
FROM REGISTROS
WHERE IDADE = '30'
AND
ENDERECO ='Minas Gerais';



/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E GRUPOS DE REGISTROS SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/

SELECT NOME,IDADE,ENDERECO, 
COUNT(*) AS 'TOTAL' 
FROM REGISTROS 
GROUP BY ENDERECO;




/* REALIZANDO A CONTAGEM COM SEPARAÇÃO DE GRUPOS COMPUTADOS*/


/* 01   CRIANDO O BANCO DE DADOS*/

CREATE DATABASE DADOS;


/*VERIFICANDO SE O BANCO FOI CRIADO*/
SHOW DATABASES;




/*USANDO O BANCO DE DADOS CRIADO*/

USE DADOS;


/* 02   CRIANDO A TABELA */

CREATE TABLE REGISTROS(

NOME VARCHAR(100),
IDADE CHAR(2),
TELEFONE VARCHAR(100),
ENDERECO VARCHAR(100)

);





/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/

DESCRIBE REGISTROS;

/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/

INSERT INTO REGISTROS(NOME,IDADE,TELEFONE,ENDERECO)
VALUES
('Maxswell Diniz',30,'116484545','São Paulo'),('Camila Muniz',35,'21458788','Rio de Janeiro'),('Paulo Ricardo',26,'117878788','São Paulo'),
('Sandra Cabrito',45,'21548445464','Rio de Janeiro'),('Tania Ferraz',30,'1195225225','São Paulo'),('Viviane araujo',31,'61454887','Minas Gerais');




/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/

SELECT * FROM REGISTROS;




/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/

SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%Paulo';
SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE 'Rio%';
SELECT NOME,IDADE,TELEFONE,ENDERECO FROM REGISTROS WHERE ENDERECO LIKE '%de%';



/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/

SELECT ENDERECO,
COUNT(*) AS 'TOTAL'
FROM REGISTROS
GROUP BY ENDERECO;

SELECT IDADE,
COUNT(*) AS 'TOTAL'
FROM REGISTROS
GROUP BY IDADE;

SELECT NOME,IDADE,TELEFONE,ENDERECO 
FROM REGISTROS
WHERE ENDERECO = 'Rio de Janeiro'
OR
IDADE = '15';




/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/

SELECT NOME,IDADE,TELEFONE,ENDERECO
FROM REGISTROS
WHERE IDADE = '30'
AND
ENDERECO = 'São Paulo';

/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E GRUPOS DE REGISTROS SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/

SELECT ENDERECO,
COUNT(*) AS 'TOTAL'
FROM REGISTROS
GROUP BY ENDERECO;

SELECT IDADE,
COUNT(*) AS 'TOTAL'
FROM REGISTROS
GROUP BY IDADE;



/* REALIZANDO A CONTAGEM COM SEPARAÇÃO DE GRUPOS COMPUTADOS*/











































/* 01   CRIANDO O BANCO DE DADOS*/





/*VERIFICANDO SE O BANCO FOI CRIADO*/




/*USANDO O BANCO DE DADOS CRIADO*/


/* 02   CRIANDO A TABELA */






/*VERIFICANDO A ESTRUTURA DA TABELA E SE A TABELA FOI CRIADA*/


/*CRIANDO OS REGISTROS NA TABELA COM INSERT*/




/* 03 - REALIZANDO AS PROJEÇÕES E FILTROS SELECT*/



/* 04 - REALIZE A PROJEÇÃO USANDO LIKE E DEFINE A PRIMEIRA PALAVRA E A ULTIMA PARA O FILTRO*/




/* 05 - REALIZANDO BUSCAS E CONDIÇÕES, VERIFIQUE SE O REGISTRO SE TEM DADOS DE RIO DE JANEIRO EM UMA COLUNA E A IDADE DE 15
DEPOIS REALIZE UMA CONDIÇÃO DE DADOS DE SÃO PAULO COM 30 ANOS.*/

/* REALIZANDO O FILTRO COM CONDIÇÕES OU / OR*/




/* REALIZANDO O FILTRO PRECISO QUE CONSTE OS DADOS TANTO EM UMA COLUNA QUANTO NA OUTRA*/



/* 06 - REALIZANDO A CONTAGEM DE REGISTROS REPETIDO COM SEPARAÇÃO E GRUPOS DE REGISTROS SUBSTITUA A PALAVRA COUNT PARA NÃO APARECER*/




/* REALIZANDO A CONTAGEM COM SEPARAÇÃO DE GRUPOS COMPUTADOS*/






-- AULA 06 INICIANDO CAMPO DE FILTROS DE VALORES NULOS, UPDATE E DELETE DE REGISTROS

SHOW TABLES;
DESCRIBE CLIENTE;
SELECT * FROM CLIENTE; -- VERIFICANDO ANTES AS LISTAS DE DADOS CADASTRADO QUE TENHA VALORES NULOS

-- 01 FILTRANDO VALORES NULOS:

-- USAMOS SEMPRE O (Is NULL) QUE SIGNIFICA É PARA MOSTRAR OS DADOS QUE TEM NULOS
SELECT NOME,SEXO,ENDERECO FROM CLIENTE WHERE EMAIL Is NULL;  

-- PARA TRAZER SÓ OS DADOS QUE NÃO TENHA VALORES NULOS USAMOS O TERMO (Is Not NULL)

SELECT NOME,SEXO,ENDERECO FROM CLIENTE WHERE EMAIL  Is Not Null;

-- 02 DA AULA 06 CRIANDO O UPDATE A ATUALIZAÇÃO DOS DADOS

-- ATUALIZANDO OS DADOS DOS CLIENTES QUE TEM OS DADOS ERRADOS OU NÃO REGISTRADOS COMO VALORES NULOS
-- USAMOS UPDATE NOMETABELA SET COLUNA QUE DESEJA MODIFICAR E COLOQUE OS DADOS, DEPOIS FILTRAMOS WHERE E O NOME DO CLIENTE REFERÊNCIA QUE DESEJA MODIFICAR.

SELECT * FROM CLIENTE WHERE NOME = 'MÁRCIO DINIZ'; -- PRIMEIRO FILTRAMOS O REGISTRO QUE DESEJA REALIZAR O UPDADTE

UPDATE CLIENTE SET EMAIL ='marciodiniz@gmai.com' WHERE NOME = 'MÁRCIO DINIZ';

SELECT * FROM CLIENTE WHERE NOME = 'SAMYA DINIZ';

UPDATE CLIENTE SET EMAIL ='samyadiniz@yahoo.com' WHERE NOME ='Samya Diniz';

-- 03 DA AULA 06 REALIZANDO O COMANDO DELETE USE SEMPRE WHERE PARA NÃO APAGAR TUDO. REALIZE OS FILTROS ANTES

SELECT * FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'MAXSWELL SOUSA DINIZ';

DELETE FROM CLIENTE WHERE NOME ='MAXSWELL SOUSA DINIZ';

-- 04 DA AULA 06 DELETANDO NOME ESPECÍFICO QUANDO SE TEM OUTROS NOMES OU DADOS QUE DESEJA

INSERT INTO CLIENTE VALUES('SANDRA',454558787,'sandra@gmail.com','1215-45445','Rua Fernando ','F');
INSERT INTO CLIENTE VALUES('SANDRA',45459832,'sandra@yahoo.com','68944545-454','Fernando linute ','F');

SELECT * FROM CLIENTE; -- VISUALIZANDO TODOS OS CLIANTES

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'SANDRA'; -- REALIZANDO A CONTAGEM DE REGISTROS COM ESSE NOME

SELECT * FROM CLIENTE WHERE NOME = 'SANDRA'; -- VISUALIZANDO OS REGISTROS COM ESSE NOME

-- DEFINIMOS UMA CONDIÇÃO AND PARA DELETARMOS OS DADOS CORRETOS

DELETE FROM CLIENTE WHERE NOME = 'SANDRA' AND EMAIL = 'sandra@yahoo.com';


























